### ISSUE TITLE
SDL upgrade

### ISSUE THREAD

**Issue by awong26** [BLAM-Lab-Projects/experiment-code#11]
We should upgrade SDL from 1.2 to 2. This requires more than simply swapping out the SDL folder, so it will take some work. However, SDL 2.0 provides some important advantages (e.g., it improves graphics handing and allows for digitizing tablet inputs).

https://wiki.libsdl.org/MigrationGuide

https://www.libsdl.org/download-2.0.php

**Comment by aforren1** [comment]
We could include something like https://github.com/spurious/SDL-mirror as a submodule. To do that, call

```
git submodule add https://github.com/spurious/SDL-mirror
```

in the top-level directory, and after cloning,

```
git submodule init
git submodule update
```

or (identically):

```
git clone --recursive https://github.com/blam-lab-projects/experiment-code
```

To update the submodule, something like

```
git submodule update --remote --merge
```

This makes it somewhat easier to keep up-to-date (at least from a certain point of view), or roll to a specific version if necessary.
(ref https://git-scm.com/book/en/v2/Git-Tools-Submodules)

**Comment by awong26** [comment]
Please note, the SDL2 upgrade will take place in a separate repository.
